{'nform': {'Inventory-automaticservicedetection': 'on',
           'MultisiteWATO': 'off',
           'Notification': 'off',
           'OperationmodeofCheck_MK': 'off',
           'UserManagement': 'off'},
 'views': {'Addons': 'on',
           'Business Intelligence': 'on',
           'Dashboards': 'on',
           'Event Console': 'on',
           'Hostgroups': 'on',
           'Hosts': 'on',
           'Problems': 'on',
           'Servicegroups': 'on',
           'Services': 'on'}}
