<?php
// Created by Multisite UserDB Hook (users-saved)
global $mk_users, $mk_roles, $mk_folders;
$mk_users   = array(
    'nagiosadmin' => array(
        'alias' => 'nagiosadmin',
        'locked' => false,
        'language' => null,
        'roles' => array(
            'admin',
        ),
    ),
);
$mk_roles   = array(
    'admin' => array(
        'action.reschedule',
        'action.notifications',
        'action.enablechecks',
        'action.clearmodattr',
        'action.fakechecks',
        'action.customnotification',
        'action.acknowledge',
        'action.addcomment',
        'action.downtimes',
        'mkeventd.update',
        'mkeventd.update_comment',
        'mkeventd.update_contact',
        'mkeventd.changestate',
        'mkeventd.actions',
        'mkeventd.delete',
        'view.mobile_notifications',
        'view.aggr_service',
        'view.ec_events_of_host',
        'view.hostgroupservices',
        'view.searchpnp',
        'view.hosttiles',
        'view.nagstamon_hosts',
        'view.servicegroup',
        'view.allhosts',
        'view.hostevents',
        'view.aggr_single_api',
        'view.downtimes_of_host',
        'view.searchsvc',
        'view.host_pending',
        'view.aggr_all',
        'view.mobile_svcproblems_unack',
        'view.hoststatus',
        'view.servicedesc',
        'view.problemsofhost',
        'view.hostgroupgrid',
        'view.mobile_hostproblems',
        'view.mobile_hostsvcevents',
        'view.notifications',
        'view.svcbygroups',
        'view.comments_of_host',
        'view.host_crit',
        'view.host_unknown',
        'view.ec_history_of_host',
        'view.logfile',
        'view.nagstamon_svc',
        'view.ec_history_of_event',
        'view.hostpnp',
        'view.sitesvcs',
        'view.mobile_svcproblems',
        'view.aggr_summary',
        'view.mobile_contactnotifications',
        'view.host_export',
        'view.hostgroup',
        'view.sitehosts',
        'view.ec_historyentry',
        'view.mobile_events',
        'view.hosts',
        'view.uncheckedsvc',
        'view.aggr_singlehosts',
        'view.downtimes_of_service',
        'view.allservices',
        'view.mobile_hostsvcnotifications',
        'view.servicedescpnp',
        'view.ec_history_recent',
        'view.hostgroups',
        'view.svcproblems',
        'view.mobile_svcevents',
        'view.aggr_group',
        'view.hostproblems',
        'view.searchhost',
        'view.hostsvcevents',
        'view.svcproblems_dash',
        'view.mobile_hostproblems_unack',
        'view.downtimes',
        'view.hostproblems_dash',
        'view.aggr_host',
        'view.comments',
        'view.aggr_problems',
        'view.mobile_hoststatus',
        'view.hostnotifications',
        'view.host_warn',
        'view.comments_of_service',
        'view.svcbyhgroups',
        'view.contactnotifications',
        'view.events',
        'view.events_dash',
        'view.ec_events',
        'view.host_ok',
        'view.ec_event',
        'view.mobile_searchsvc',
        'view.hostsvcnotifications',
        'view.mobile_searchhost',
        'view.aggr_hostnameaggrs',
        'view.host',
        'view.pendingsvc',
        'view.mobile_svcnotifications',
        'view.hostsbygroup',
        'view.mobile_host',
        'view.service',
        'view.svcgroups',
        'view.aggr_hostproblems',
        'view.svcnotifications',
        'view.alertstats',
        'view.allhosts_mini',
        'view.recentsvc',
        'view.aggr_singlehost',
        'view.aggr_hostgroup_boxed',
        'view.aggr_single',
        'view.mobile_service',
        'view.svcevents',
        'view.ec_events_of_monhost',
        'view.svcgroups_grid',
        'sidesnap.custom_links',
        'sidesnap.nagios_legacy',
        'sidesnap.summary_hosts',
        'sidesnap.wato',
        'sidesnap.admin_mini',
        'sidesnap.bookmarks',
        'sidesnap.speedometer',
        'sidesnap.biaggr_groups',
        'sidesnap.tactical_overview',
        'sidesnap.master_control',
        'sidesnap.sitestatus',
        'sidesnap.wato_foldertree',
        'sidesnap.performance',
        'sidesnap.mkeventd_performance',
        'sidesnap.problem_hosts',
        'sidesnap.nagvis_maps',
        'sidesnap.views',
        'sidesnap.hostgroups',
        'sidesnap.search',
        'sidesnap.hostmatrix',
        'sidesnap.about',
        'sidesnap.admin',
        'sidesnap.servicegroups',
        'sidesnap.hosts',
        'sidesnap.time',
        'wato.use',
        'wato.edit',
        'wato.seeall',
        'wato.activate',
        'wato.activateforeign',
        'wato.auditlog',
        'wato.hosts',
        'wato.edit_hosts',
        'wato.parentscan',
        'wato.move_hosts',
        'wato.manage_hosts',
        'wato.clone_hosts',
        'wato.services',
        'wato.edit_folders',
        'wato.manage_folders',
        'wato.see_all_folders',
        'wato.all_folders',
        'wato.hosttags',
        'wato.global',
        'wato.rulesets',
        'wato.groups',
        'wato.timeperiods',
        'wato.sites',
        'wato.automation',
        'wato.users',
        'wato.snapshots',
        'wato.pattern_editor',
        'mkeventd.edit',
        'mkeventd.activate',
        'mkeventd.switchmode',
        'nagvis.*_*_*',
        'bi.see_all',
        'general.use',
        'general.see_all',
        'general.edit_views',
        'general.publish_views',
        'general.force_views',
        'general.view_option_columns',
        'general.view_option_refresh',
        'general.painter_options',
        'general.act',
        'general.see_sidebar',
        'general.configure_sidebar',
        'general.edit_profile',
        'general.edit_notifications',
        'general.edit_user_attributes',
        'general.change_password',
        'general.logout',
        'general.ignore_soft_limit',
        'general.ignore_hard_limit',
    ),
    'user' => array(
        'action.reschedule',
        'action.customnotification',
        'action.acknowledge',
        'action.addcomment',
        'action.downtimes',
        'mkeventd.update',
        'mkeventd.update_comment',
        'mkeventd.update_contact',
        'mkeventd.changestate',
        'mkeventd.actions',
        'mkeventd.delete',
        'view.mobile_notifications',
        'view.aggr_service',
        'view.ec_events_of_host',
        'view.hostgroupservices',
        'view.searchpnp',
        'view.hosttiles',
        'view.nagstamon_hosts',
        'view.servicegroup',
        'view.allhosts',
        'view.hostevents',
        'view.aggr_single_api',
        'view.downtimes_of_host',
        'view.searchsvc',
        'view.host_pending',
        'view.aggr_all',
        'view.mobile_svcproblems_unack',
        'view.hoststatus',
        'view.servicedesc',
        'view.problemsofhost',
        'view.hostgroupgrid',
        'view.mobile_hostproblems',
        'view.mobile_hostsvcevents',
        'view.notifications',
        'view.svcbygroups',
        'view.comments_of_host',
        'view.host_crit',
        'view.host_unknown',
        'view.ec_history_of_host',
        'view.logfile',
        'view.nagstamon_svc',
        'view.ec_history_of_event',
        'view.hostpnp',
        'view.sitesvcs',
        'view.mobile_svcproblems',
        'view.aggr_summary',
        'view.mobile_contactnotifications',
        'view.host_export',
        'view.hostgroup',
        'view.sitehosts',
        'view.ec_historyentry',
        'view.mobile_events',
        'view.hosts',
        'view.uncheckedsvc',
        'view.aggr_singlehosts',
        'view.downtimes_of_service',
        'view.allservices',
        'view.mobile_hostsvcnotifications',
        'view.servicedescpnp',
        'view.ec_history_recent',
        'view.hostgroups',
        'view.svcproblems',
        'view.mobile_svcevents',
        'view.aggr_group',
        'view.hostproblems',
        'view.searchhost',
        'view.hostsvcevents',
        'view.svcproblems_dash',
        'view.mobile_hostproblems_unack',
        'view.downtimes',
        'view.hostproblems_dash',
        'view.aggr_host',
        'view.comments',
        'view.aggr_problems',
        'view.mobile_hoststatus',
        'view.hostnotifications',
        'view.host_warn',
        'view.comments_of_service',
        'view.svcbyhgroups',
        'view.contactnotifications',
        'view.events',
        'view.events_dash',
        'view.ec_events',
        'view.host_ok',
        'view.ec_event',
        'view.mobile_searchsvc',
        'view.hostsvcnotifications',
        'view.mobile_searchhost',
        'view.aggr_hostnameaggrs',
        'view.host',
        'view.pendingsvc',
        'view.mobile_svcnotifications',
        'view.hostsbygroup',
        'view.mobile_host',
        'view.service',
        'view.svcgroups',
        'view.aggr_hostproblems',
        'view.svcnotifications',
        'view.alertstats',
        'view.allhosts_mini',
        'view.recentsvc',
        'view.aggr_singlehost',
        'view.aggr_hostgroup_boxed',
        'view.aggr_single',
        'view.mobile_service',
        'view.svcevents',
        'view.ec_events_of_monhost',
        'view.svcgroups_grid',
        'sidesnap.custom_links',
        'sidesnap.nagios_legacy',
        'sidesnap.summary_hosts',
        'sidesnap.wato',
        'sidesnap.admin_mini',
        'sidesnap.bookmarks',
        'sidesnap.biaggr_groups',
        'sidesnap.tactical_overview',
        'sidesnap.sitestatus',
        'sidesnap.wato_foldertree',
        'sidesnap.problem_hosts',
        'sidesnap.nagvis_maps',
        'sidesnap.views',
        'sidesnap.hostgroups',
        'sidesnap.search',
        'sidesnap.hostmatrix',
        'sidesnap.about',
        'sidesnap.admin',
        'sidesnap.servicegroups',
        'sidesnap.hosts',
        'sidesnap.time',
        'wato.use',
        'wato.edit',
        'wato.activate',
        'wato.hosts',
        'wato.edit_hosts',
        'wato.parentscan',
        'wato.move_hosts',
        'wato.manage_hosts',
        'wato.clone_hosts',
        'wato.services',
        'wato.edit_folders',
        'wato.manage_folders',
        'wato.rulesets',
        'wato.pattern_editor',
        'general.use',
        'general.edit_views',
        'general.publish_views',
        'general.view_option_columns',
        'general.view_option_refresh',
        'general.painter_options',
        'general.act',
        'general.see_sidebar',
        'general.configure_sidebar',
        'general.edit_profile',
        'general.edit_notifications',
        'general.edit_user_attributes',
        'general.change_password',
        'general.logout',
        'general.ignore_soft_limit',
    ),
    'guest' => array(
        'view.mobile_notifications',
        'view.aggr_service',
        'view.ec_events_of_host',
        'view.hostgroupservices',
        'view.searchpnp',
        'view.hosttiles',
        'view.nagstamon_hosts',
        'view.servicegroup',
        'view.allhosts',
        'view.hostevents',
        'view.aggr_single_api',
        'view.downtimes_of_host',
        'view.searchsvc',
        'view.host_pending',
        'view.aggr_all',
        'view.mobile_svcproblems_unack',
        'view.hoststatus',
        'view.servicedesc',
        'view.problemsofhost',
        'view.hostgroupgrid',
        'view.mobile_hostproblems',
        'view.mobile_hostsvcevents',
        'view.notifications',
        'view.svcbygroups',
        'view.comments_of_host',
        'view.host_crit',
        'view.host_unknown',
        'view.ec_history_of_host',
        'view.logfile',
        'view.nagstamon_svc',
        'view.ec_history_of_event',
        'view.hostpnp',
        'view.sitesvcs',
        'view.mobile_svcproblems',
        'view.aggr_summary',
        'view.mobile_contactnotifications',
        'view.host_export',
        'view.hostgroup',
        'view.sitehosts',
        'view.ec_historyentry',
        'view.mobile_events',
        'view.hosts',
        'view.uncheckedsvc',
        'view.aggr_singlehosts',
        'view.downtimes_of_service',
        'view.allservices',
        'view.mobile_hostsvcnotifications',
        'view.servicedescpnp',
        'view.ec_history_recent',
        'view.hostgroups',
        'view.svcproblems',
        'view.mobile_svcevents',
        'view.aggr_group',
        'view.hostproblems',
        'view.searchhost',
        'view.hostsvcevents',
        'view.svcproblems_dash',
        'view.mobile_hostproblems_unack',
        'view.downtimes',
        'view.hostproblems_dash',
        'view.aggr_host',
        'view.comments',
        'view.aggr_problems',
        'view.mobile_hoststatus',
        'view.hostnotifications',
        'view.host_warn',
        'view.comments_of_service',
        'view.svcbyhgroups',
        'view.contactnotifications',
        'view.events',
        'view.events_dash',
        'view.ec_events',
        'view.host_ok',
        'view.ec_event',
        'view.mobile_searchsvc',
        'view.hostsvcnotifications',
        'view.mobile_searchhost',
        'view.aggr_hostnameaggrs',
        'view.host',
        'view.pendingsvc',
        'view.mobile_svcnotifications',
        'view.hostsbygroup',
        'view.mobile_host',
        'view.service',
        'view.svcgroups',
        'view.aggr_hostproblems',
        'view.svcnotifications',
        'view.alertstats',
        'view.allhosts_mini',
        'view.recentsvc',
        'view.aggr_singlehost',
        'view.aggr_hostgroup_boxed',
        'view.aggr_single',
        'view.mobile_service',
        'view.svcevents',
        'view.ec_events_of_monhost',
        'view.svcgroups_grid',
        'sidesnap.custom_links',
        'sidesnap.nagios_legacy',
        'sidesnap.summary_hosts',
        'sidesnap.wato',
        'sidesnap.bookmarks',
        'sidesnap.biaggr_groups',
        'sidesnap.tactical_overview',
        'sidesnap.wato_foldertree',
        'sidesnap.problem_hosts',
        'sidesnap.nagvis_maps',
        'sidesnap.views',
        'sidesnap.hostgroups',
        'sidesnap.search',
        'sidesnap.hostmatrix',
        'sidesnap.about',
        'sidesnap.servicegroups',
        'sidesnap.hosts',
        'sidesnap.time',
        'nagvis.Map_view_*',
        'bi.see_all',
        'general.use',
        'general.see_all',
        'general.view_option_columns',
        'general.painter_options',
        'general.see_sidebar',
        'general.logout',
    ),
);
$mk_folders = array(
    'nagiosadmin' => array(
        '' => array(
            'read' => true,
            'write' => true,
        ),
    ),
);

function get_folder_permissions($username) {
    global $mk_folders;
    if(!isset($mk_folders[$username])) {
        return array();
    } else {
        return $mk_folders[$username];
    }
}

function all_users() {
    global $mk_users;
    return $mk_users;
}

function user_roles($username) {
    global $mk_users;
    if(!isset($mk_users[$username]))
        return array();
    else
        return $mk_users[$username]['roles'];
}

function user_permissions($username) {
    global $mk_roles;
    $permissions = array();

    foreach(user_roles($username) AS $role)
        $permissions = array_merge($permissions, $mk_roles[$role]);

    // Make the array uniq
    array_flip($permissions);
    array_flip($permissions);

    return $permissions;
}

function users_with_role($want_role) {
    global $mk_users, $mk_roles;
    $result = array();
    foreach($mk_users AS $username => $user) {
        foreach($user['roles'] AS $role) {
            if($want_role == $role) {
                $result[] = $username;
            }
        }
    }
    return $result;
}

function roles_with_permission($want_permission) {
    global $mk_roles;
    $result = array();
    foreach($mk_roles AS $rolename => $role) {
        foreach($role AS $permission) {
            if($permission == $want_permission) {
                $result[] = $rolename;
                break;
            }
        }
    }
    return $result;
}

function users_with_permission($need_permission) {
    global $mk_users;
    $result = array();
    foreach(roles_with_permission($need_permission) AS $rolename) {
        $result = array_merge($result, users_with_role($rolename));
    }
    return $result;
}

function may($username, $need_permission) {
    global $mk_roles;
    foreach(user_roles($username) AS $role) {
        foreach($mk_roles[$role] AS $permission) {
            if($need_permission == $permission) {
                return true;
            }
        }
    }
    return false;
}

?>
